// Code generated by goctl. DO NOT EDIT!
// Source: intranet.proto

package intranet

import (
	"context"

	"ywadmin-v3/service/intranet/rpc/intranetclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddInsideHostInfoReq           = intranetclient.AddInsideHostInfoReq
	AddInsideInstallPlanReq        = intranetclient.AddInsideInstallPlanReq
	AddInsideOperationReq          = intranetclient.AddInsideOperationReq
	AddInsideProjectClusterReq     = intranetclient.AddInsideProjectClusterReq
	AddInsideProxyHostReq          = intranetclient.AddInsideProxyHostReq
	AddInsideServerReq             = intranetclient.AddInsideServerReq
	AddInsideTasksLogsReq          = intranetclient.AddInsideTasksLogsReq
	AddInsideTasksPidReq           = intranetclient.AddInsideTasksPidReq
	AddInsideTasksReq              = intranetclient.AddInsideTasksReq
	AddInsideVersionReq            = intranetclient.AddInsideVersionReq
	DeleteInsideHostInfoReq        = intranetclient.DeleteInsideHostInfoReq
	DeleteInsideInstallPlanReq     = intranetclient.DeleteInsideInstallPlanReq
	DeleteInsideOperationReq       = intranetclient.DeleteInsideOperationReq
	DeleteInsideProjectClusterReq  = intranetclient.DeleteInsideProjectClusterReq
	DeleteInsideProxyHostReq       = intranetclient.DeleteInsideProxyHostReq
	DeleteInsideServerReq          = intranetclient.DeleteInsideServerReq
	DeleteInsideTasksLogsReq       = intranetclient.DeleteInsideTasksLogsReq
	DeleteInsideTasksPidReq        = intranetclient.DeleteInsideTasksPidReq
	DeleteInsideTasksReq           = intranetclient.DeleteInsideTasksReq
	DeleteInsideVersionReq         = intranetclient.DeleteInsideVersionReq
	GetInsideHostInfoReq           = intranetclient.GetInsideHostInfoReq
	GetInsideInstallPlanReq        = intranetclient.GetInsideInstallPlanReq
	GetInsideOperationReq          = intranetclient.GetInsideOperationReq
	GetInsideProjectClusterReq     = intranetclient.GetInsideProjectClusterReq
	GetInsideProxyHostReq          = intranetclient.GetInsideProxyHostReq
	GetInsideServerReq             = intranetclient.GetInsideServerReq
	GetInsideTasksLogsReq          = intranetclient.GetInsideTasksLogsReq
	GetInsideTasksPidReq           = intranetclient.GetInsideTasksPidReq
	GetInsideTasksReq              = intranetclient.GetInsideTasksReq
	GetInsideVersionReq            = intranetclient.GetInsideVersionReq
	InsideHostInfoCommon           = intranetclient.InsideHostInfoCommon
	InsideHostInfoCommonResp       = intranetclient.InsideHostInfoCommonResp
	InsideInstallPlanCommon        = intranetclient.InsideInstallPlanCommon
	InsideInstallPlanCommonResp    = intranetclient.InsideInstallPlanCommonResp
	InsideOperationCommon          = intranetclient.InsideOperationCommon
	InsideOperationCommonResp      = intranetclient.InsideOperationCommonResp
	InsideProjectClusterCommon     = intranetclient.InsideProjectClusterCommon
	InsideProjectClusterCommonResp = intranetclient.InsideProjectClusterCommonResp
	InsideProxyHostCommon          = intranetclient.InsideProxyHostCommon
	InsideProxyHostCommonResp      = intranetclient.InsideProxyHostCommonResp
	InsideServerCommon             = intranetclient.InsideServerCommon
	InsideServerCommonResp         = intranetclient.InsideServerCommonResp
	InsideTasksCommon              = intranetclient.InsideTasksCommon
	InsideTasksCommonResp          = intranetclient.InsideTasksCommonResp
	InsideTasksLogsCommon          = intranetclient.InsideTasksLogsCommon
	InsideTasksLogsCommonResp      = intranetclient.InsideTasksLogsCommonResp
	InsideTasksOperationReq        = intranetclient.InsideTasksOperationReq
	InsideTasksOperationResp       = intranetclient.InsideTasksOperationResp
	InsideTasksPidCommon           = intranetclient.InsideTasksPidCommon
	InsideTasksPidCommonResp       = intranetclient.InsideTasksPidCommonResp
	InsideVersionCommon            = intranetclient.InsideVersionCommon
	InsideVersionCommonResp        = intranetclient.InsideVersionCommonResp
	ListInsideHostInfoData         = intranetclient.ListInsideHostInfoData
	ListInsideHostInfoReq          = intranetclient.ListInsideHostInfoReq
	ListInsideHostInfoResp         = intranetclient.ListInsideHostInfoResp
	ListInsideInstallPlanData      = intranetclient.ListInsideInstallPlanData
	ListInsideInstallPlanReq       = intranetclient.ListInsideInstallPlanReq
	ListInsideInstallPlanResp      = intranetclient.ListInsideInstallPlanResp
	ListInsideOperationData        = intranetclient.ListInsideOperationData
	ListInsideOperationReq         = intranetclient.ListInsideOperationReq
	ListInsideOperationResp        = intranetclient.ListInsideOperationResp
	ListInsideProjectClusterData   = intranetclient.ListInsideProjectClusterData
	ListInsideProjectClusterReq    = intranetclient.ListInsideProjectClusterReq
	ListInsideProjectClusterResp   = intranetclient.ListInsideProjectClusterResp
	ListInsideProxyHostData        = intranetclient.ListInsideProxyHostData
	ListInsideProxyHostReq         = intranetclient.ListInsideProxyHostReq
	ListInsideProxyHostResp        = intranetclient.ListInsideProxyHostResp
	ListInsideServerData           = intranetclient.ListInsideServerData
	ListInsideServerReq            = intranetclient.ListInsideServerReq
	ListInsideServerResp           = intranetclient.ListInsideServerResp
	ListInsideTasksData            = intranetclient.ListInsideTasksData
	ListInsideTasksLogsData        = intranetclient.ListInsideTasksLogsData
	ListInsideTasksLogsReq         = intranetclient.ListInsideTasksLogsReq
	ListInsideTasksLogsResp        = intranetclient.ListInsideTasksLogsResp
	ListInsideTasksPidData         = intranetclient.ListInsideTasksPidData
	ListInsideTasksPidReq          = intranetclient.ListInsideTasksPidReq
	ListInsideTasksPidResp         = intranetclient.ListInsideTasksPidResp
	ListInsideTasksReq             = intranetclient.ListInsideTasksReq
	ListInsideTasksResp            = intranetclient.ListInsideTasksResp
	ListInsideVersionData          = intranetclient.ListInsideVersionData
	ListInsideVersionReq           = intranetclient.ListInsideVersionReq
	ListInsideVersionResp          = intranetclient.ListInsideVersionResp
	UpdateInsideHostInfoReq        = intranetclient.UpdateInsideHostInfoReq
	UpdateInsideInstallPlanReq     = intranetclient.UpdateInsideInstallPlanReq
	UpdateInsideOperationReq       = intranetclient.UpdateInsideOperationReq
	UpdateInsideProjectClusterReq  = intranetclient.UpdateInsideProjectClusterReq
	UpdateInsideProxyHostReq       = intranetclient.UpdateInsideProxyHostReq
	UpdateInsideServerReq          = intranetclient.UpdateInsideServerReq
	UpdateInsideTasksLogsReq       = intranetclient.UpdateInsideTasksLogsReq
	UpdateInsideTasksPidReq        = intranetclient.UpdateInsideTasksPidReq
	UpdateInsideTasksReq           = intranetclient.UpdateInsideTasksReq
	UpdateInsideVersionReq         = intranetclient.UpdateInsideVersionReq

	Intranet interface {
		// InsideInstallPlan Rpc Start
		InsideInstallPlanAdd(ctx context.Context, in *AddInsideInstallPlanReq, opts ...grpc.CallOption) (*InsideInstallPlanCommonResp, error)
		InsideInstallPlanUpdate(ctx context.Context, in *UpdateInsideInstallPlanReq, opts ...grpc.CallOption) (*InsideInstallPlanCommonResp, error)
		InsideInstallPlanDelete(ctx context.Context, in *DeleteInsideInstallPlanReq, opts ...grpc.CallOption) (*InsideInstallPlanCommonResp, error)
		InsideInstallPlanGet(ctx context.Context, in *GetInsideInstallPlanReq, opts ...grpc.CallOption) (*ListInsideInstallPlanData, error)
		InsideInstallPlanList(ctx context.Context, in *ListInsideInstallPlanReq, opts ...grpc.CallOption) (*ListInsideInstallPlanResp, error)
		// InsideInstallPlan Rpc End
		InsideOperationAdd(ctx context.Context, in *AddInsideOperationReq, opts ...grpc.CallOption) (*InsideOperationCommonResp, error)
		InsideOperationUpdate(ctx context.Context, in *UpdateInsideOperationReq, opts ...grpc.CallOption) (*InsideOperationCommonResp, error)
		InsideOperationDelete(ctx context.Context, in *DeleteInsideOperationReq, opts ...grpc.CallOption) (*InsideOperationCommonResp, error)
		InsideOperationGet(ctx context.Context, in *GetInsideOperationReq, opts ...grpc.CallOption) (*ListInsideOperationData, error)
		InsideOperationList(ctx context.Context, in *ListInsideOperationReq, opts ...grpc.CallOption) (*ListInsideOperationResp, error)
		// InsideOperation Rpc End
		InsideProjectClusterAdd(ctx context.Context, in *AddInsideProjectClusterReq, opts ...grpc.CallOption) (*InsideProjectClusterCommonResp, error)
		InsideProjectClusterUpdate(ctx context.Context, in *UpdateInsideProjectClusterReq, opts ...grpc.CallOption) (*InsideProjectClusterCommonResp, error)
		InsideProjectClusterDelete(ctx context.Context, in *DeleteInsideProjectClusterReq, opts ...grpc.CallOption) (*InsideProjectClusterCommonResp, error)
		InsideProjectClusterGet(ctx context.Context, in *GetInsideProjectClusterReq, opts ...grpc.CallOption) (*ListInsideProjectClusterData, error)
		InsideProjectClusterList(ctx context.Context, in *ListInsideProjectClusterReq, opts ...grpc.CallOption) (*ListInsideProjectClusterResp, error)
		// InsideProjectCluster Rpc End
		InsideProxyHostAdd(ctx context.Context, in *AddInsideProxyHostReq, opts ...grpc.CallOption) (*InsideProxyHostCommonResp, error)
		InsideProxyHostUpdate(ctx context.Context, in *UpdateInsideProxyHostReq, opts ...grpc.CallOption) (*InsideProxyHostCommonResp, error)
		InsideProxyHostDelete(ctx context.Context, in *DeleteInsideProxyHostReq, opts ...grpc.CallOption) (*InsideProxyHostCommonResp, error)
		InsideProxyHostGet(ctx context.Context, in *GetInsideProxyHostReq, opts ...grpc.CallOption) (*ListInsideProxyHostData, error)
		InsideProxyHostList(ctx context.Context, in *ListInsideProxyHostReq, opts ...grpc.CallOption) (*ListInsideProxyHostResp, error)
		// InsideServer Rpc Start
		InsideServerAdd(ctx context.Context, in *AddInsideServerReq, opts ...grpc.CallOption) (*InsideServerCommonResp, error)
		InsideServerUpdate(ctx context.Context, in *UpdateInsideServerReq, opts ...grpc.CallOption) (*InsideServerCommonResp, error)
		InsideServerDelete(ctx context.Context, in *DeleteInsideServerReq, opts ...grpc.CallOption) (*InsideServerCommonResp, error)
		InsideServerGet(ctx context.Context, in *GetInsideServerReq, opts ...grpc.CallOption) (*ListInsideServerData, error)
		InsideServerList(ctx context.Context, in *ListInsideServerReq, opts ...grpc.CallOption) (*ListInsideServerResp, error)
		// InsideServer Rpc End
		InsideTasksAdd(ctx context.Context, in *AddInsideTasksReq, opts ...grpc.CallOption) (*InsideTasksCommonResp, error)
		InsideTasksUpdate(ctx context.Context, in *UpdateInsideTasksReq, opts ...grpc.CallOption) (*InsideTasksCommonResp, error)
		InsideTasksDelete(ctx context.Context, in *DeleteInsideTasksReq, opts ...grpc.CallOption) (*InsideTasksCommonResp, error)
		InsideTasksGet(ctx context.Context, in *GetInsideTasksReq, opts ...grpc.CallOption) (*ListInsideTasksData, error)
		InsideTasksList(ctx context.Context, in *ListInsideTasksReq, opts ...grpc.CallOption) (*ListInsideTasksResp, error)
		InsideTasksOperation(ctx context.Context, in *InsideTasksOperationReq, opts ...grpc.CallOption) (*InsideTasksOperationResp, error)
		// InsideTasks Rpc End
		InsideTasksLogsAdd(ctx context.Context, in *AddInsideTasksLogsReq, opts ...grpc.CallOption) (*InsideTasksLogsCommonResp, error)
		InsideTasksLogsUpdate(ctx context.Context, in *UpdateInsideTasksLogsReq, opts ...grpc.CallOption) (*InsideTasksLogsCommonResp, error)
		InsideTasksLogsDelete(ctx context.Context, in *DeleteInsideTasksLogsReq, opts ...grpc.CallOption) (*InsideTasksLogsCommonResp, error)
		InsideTasksLogsGet(ctx context.Context, in *GetInsideTasksLogsReq, opts ...grpc.CallOption) (*ListInsideTasksLogsData, error)
		InsideTasksLogsList(ctx context.Context, in *ListInsideTasksLogsReq, opts ...grpc.CallOption) (*ListInsideTasksLogsResp, error)
		// InsideTasksLogs Rpc End
		InsideTasksPidAdd(ctx context.Context, in *AddInsideTasksPidReq, opts ...grpc.CallOption) (*InsideTasksPidCommonResp, error)
		InsideTasksPidUpdate(ctx context.Context, in *UpdateInsideTasksPidReq, opts ...grpc.CallOption) (*InsideTasksPidCommonResp, error)
		InsideTasksPidDelete(ctx context.Context, in *DeleteInsideTasksPidReq, opts ...grpc.CallOption) (*InsideTasksPidCommonResp, error)
		InsideTasksPidGet(ctx context.Context, in *GetInsideTasksPidReq, opts ...grpc.CallOption) (*ListInsideTasksPidData, error)
		InsideTasksPidList(ctx context.Context, in *ListInsideTasksPidReq, opts ...grpc.CallOption) (*ListInsideTasksPidResp, error)
		// InsideVersion Rpc Start
		InsideVersionAdd(ctx context.Context, in *AddInsideVersionReq, opts ...grpc.CallOption) (*InsideVersionCommonResp, error)
		InsideVersionUpdate(ctx context.Context, in *UpdateInsideVersionReq, opts ...grpc.CallOption) (*InsideVersionCommonResp, error)
		InsideVersionDelete(ctx context.Context, in *DeleteInsideVersionReq, opts ...grpc.CallOption) (*InsideVersionCommonResp, error)
		InsideVersionGet(ctx context.Context, in *GetInsideVersionReq, opts ...grpc.CallOption) (*ListInsideVersionData, error)
		InsideVersionList(ctx context.Context, in *ListInsideVersionReq, opts ...grpc.CallOption) (*ListInsideVersionResp, error)
		// InsideHostInfo Rpc Start
		InsideHostInfoAdd(ctx context.Context, in *AddInsideHostInfoReq, opts ...grpc.CallOption) (*InsideHostInfoCommonResp, error)
		InsideHostInfoUpdate(ctx context.Context, in *UpdateInsideHostInfoReq, opts ...grpc.CallOption) (*InsideHostInfoCommonResp, error)
		InsideHostInfoDelete(ctx context.Context, in *DeleteInsideHostInfoReq, opts ...grpc.CallOption) (*InsideHostInfoCommonResp, error)
		InsideHostInfoGet(ctx context.Context, in *GetInsideHostInfoReq, opts ...grpc.CallOption) (*ListInsideHostInfoData, error)
		InsideHostInfoList(ctx context.Context, in *ListInsideHostInfoReq, opts ...grpc.CallOption) (*ListInsideHostInfoResp, error)
	}

	defaultIntranet struct {
		cli zrpc.Client
	}
)

func NewIntranet(cli zrpc.Client) Intranet {
	return &defaultIntranet{
		cli: cli,
	}
}

// InsideInstallPlan Rpc Start
func (m *defaultIntranet) InsideInstallPlanAdd(ctx context.Context, in *AddInsideInstallPlanReq, opts ...grpc.CallOption) (*InsideInstallPlanCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideInstallPlanAdd(ctx, in, opts...)
}

func (m *defaultIntranet) InsideInstallPlanUpdate(ctx context.Context, in *UpdateInsideInstallPlanReq, opts ...grpc.CallOption) (*InsideInstallPlanCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideInstallPlanUpdate(ctx, in, opts...)
}

func (m *defaultIntranet) InsideInstallPlanDelete(ctx context.Context, in *DeleteInsideInstallPlanReq, opts ...grpc.CallOption) (*InsideInstallPlanCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideInstallPlanDelete(ctx, in, opts...)
}

func (m *defaultIntranet) InsideInstallPlanGet(ctx context.Context, in *GetInsideInstallPlanReq, opts ...grpc.CallOption) (*ListInsideInstallPlanData, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideInstallPlanGet(ctx, in, opts...)
}

func (m *defaultIntranet) InsideInstallPlanList(ctx context.Context, in *ListInsideInstallPlanReq, opts ...grpc.CallOption) (*ListInsideInstallPlanResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideInstallPlanList(ctx, in, opts...)
}

// InsideInstallPlan Rpc End
func (m *defaultIntranet) InsideOperationAdd(ctx context.Context, in *AddInsideOperationReq, opts ...grpc.CallOption) (*InsideOperationCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideOperationAdd(ctx, in, opts...)
}

func (m *defaultIntranet) InsideOperationUpdate(ctx context.Context, in *UpdateInsideOperationReq, opts ...grpc.CallOption) (*InsideOperationCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideOperationUpdate(ctx, in, opts...)
}

func (m *defaultIntranet) InsideOperationDelete(ctx context.Context, in *DeleteInsideOperationReq, opts ...grpc.CallOption) (*InsideOperationCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideOperationDelete(ctx, in, opts...)
}

func (m *defaultIntranet) InsideOperationGet(ctx context.Context, in *GetInsideOperationReq, opts ...grpc.CallOption) (*ListInsideOperationData, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideOperationGet(ctx, in, opts...)
}

func (m *defaultIntranet) InsideOperationList(ctx context.Context, in *ListInsideOperationReq, opts ...grpc.CallOption) (*ListInsideOperationResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideOperationList(ctx, in, opts...)
}

// InsideOperation Rpc End
func (m *defaultIntranet) InsideProjectClusterAdd(ctx context.Context, in *AddInsideProjectClusterReq, opts ...grpc.CallOption) (*InsideProjectClusterCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideProjectClusterAdd(ctx, in, opts...)
}

func (m *defaultIntranet) InsideProjectClusterUpdate(ctx context.Context, in *UpdateInsideProjectClusterReq, opts ...grpc.CallOption) (*InsideProjectClusterCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideProjectClusterUpdate(ctx, in, opts...)
}

func (m *defaultIntranet) InsideProjectClusterDelete(ctx context.Context, in *DeleteInsideProjectClusterReq, opts ...grpc.CallOption) (*InsideProjectClusterCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideProjectClusterDelete(ctx, in, opts...)
}

func (m *defaultIntranet) InsideProjectClusterGet(ctx context.Context, in *GetInsideProjectClusterReq, opts ...grpc.CallOption) (*ListInsideProjectClusterData, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideProjectClusterGet(ctx, in, opts...)
}

func (m *defaultIntranet) InsideProjectClusterList(ctx context.Context, in *ListInsideProjectClusterReq, opts ...grpc.CallOption) (*ListInsideProjectClusterResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideProjectClusterList(ctx, in, opts...)
}

// InsideProjectCluster Rpc End
func (m *defaultIntranet) InsideProxyHostAdd(ctx context.Context, in *AddInsideProxyHostReq, opts ...grpc.CallOption) (*InsideProxyHostCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideProxyHostAdd(ctx, in, opts...)
}

func (m *defaultIntranet) InsideProxyHostUpdate(ctx context.Context, in *UpdateInsideProxyHostReq, opts ...grpc.CallOption) (*InsideProxyHostCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideProxyHostUpdate(ctx, in, opts...)
}

func (m *defaultIntranet) InsideProxyHostDelete(ctx context.Context, in *DeleteInsideProxyHostReq, opts ...grpc.CallOption) (*InsideProxyHostCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideProxyHostDelete(ctx, in, opts...)
}

func (m *defaultIntranet) InsideProxyHostGet(ctx context.Context, in *GetInsideProxyHostReq, opts ...grpc.CallOption) (*ListInsideProxyHostData, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideProxyHostGet(ctx, in, opts...)
}

func (m *defaultIntranet) InsideProxyHostList(ctx context.Context, in *ListInsideProxyHostReq, opts ...grpc.CallOption) (*ListInsideProxyHostResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideProxyHostList(ctx, in, opts...)
}

// InsideServer Rpc Start
func (m *defaultIntranet) InsideServerAdd(ctx context.Context, in *AddInsideServerReq, opts ...grpc.CallOption) (*InsideServerCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideServerAdd(ctx, in, opts...)
}

func (m *defaultIntranet) InsideServerUpdate(ctx context.Context, in *UpdateInsideServerReq, opts ...grpc.CallOption) (*InsideServerCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideServerUpdate(ctx, in, opts...)
}

func (m *defaultIntranet) InsideServerDelete(ctx context.Context, in *DeleteInsideServerReq, opts ...grpc.CallOption) (*InsideServerCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideServerDelete(ctx, in, opts...)
}

func (m *defaultIntranet) InsideServerGet(ctx context.Context, in *GetInsideServerReq, opts ...grpc.CallOption) (*ListInsideServerData, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideServerGet(ctx, in, opts...)
}

func (m *defaultIntranet) InsideServerList(ctx context.Context, in *ListInsideServerReq, opts ...grpc.CallOption) (*ListInsideServerResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideServerList(ctx, in, opts...)
}

// InsideServer Rpc End
func (m *defaultIntranet) InsideTasksAdd(ctx context.Context, in *AddInsideTasksReq, opts ...grpc.CallOption) (*InsideTasksCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksAdd(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksUpdate(ctx context.Context, in *UpdateInsideTasksReq, opts ...grpc.CallOption) (*InsideTasksCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksUpdate(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksDelete(ctx context.Context, in *DeleteInsideTasksReq, opts ...grpc.CallOption) (*InsideTasksCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksDelete(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksGet(ctx context.Context, in *GetInsideTasksReq, opts ...grpc.CallOption) (*ListInsideTasksData, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksGet(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksList(ctx context.Context, in *ListInsideTasksReq, opts ...grpc.CallOption) (*ListInsideTasksResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksList(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksOperation(ctx context.Context, in *InsideTasksOperationReq, opts ...grpc.CallOption) (*InsideTasksOperationResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksOperation(ctx, in, opts...)
}

// InsideTasks Rpc End
func (m *defaultIntranet) InsideTasksLogsAdd(ctx context.Context, in *AddInsideTasksLogsReq, opts ...grpc.CallOption) (*InsideTasksLogsCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksLogsAdd(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksLogsUpdate(ctx context.Context, in *UpdateInsideTasksLogsReq, opts ...grpc.CallOption) (*InsideTasksLogsCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksLogsUpdate(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksLogsDelete(ctx context.Context, in *DeleteInsideTasksLogsReq, opts ...grpc.CallOption) (*InsideTasksLogsCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksLogsDelete(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksLogsGet(ctx context.Context, in *GetInsideTasksLogsReq, opts ...grpc.CallOption) (*ListInsideTasksLogsData, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksLogsGet(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksLogsList(ctx context.Context, in *ListInsideTasksLogsReq, opts ...grpc.CallOption) (*ListInsideTasksLogsResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksLogsList(ctx, in, opts...)
}

// InsideTasksLogs Rpc End
func (m *defaultIntranet) InsideTasksPidAdd(ctx context.Context, in *AddInsideTasksPidReq, opts ...grpc.CallOption) (*InsideTasksPidCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksPidAdd(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksPidUpdate(ctx context.Context, in *UpdateInsideTasksPidReq, opts ...grpc.CallOption) (*InsideTasksPidCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksPidUpdate(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksPidDelete(ctx context.Context, in *DeleteInsideTasksPidReq, opts ...grpc.CallOption) (*InsideTasksPidCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksPidDelete(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksPidGet(ctx context.Context, in *GetInsideTasksPidReq, opts ...grpc.CallOption) (*ListInsideTasksPidData, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksPidGet(ctx, in, opts...)
}

func (m *defaultIntranet) InsideTasksPidList(ctx context.Context, in *ListInsideTasksPidReq, opts ...grpc.CallOption) (*ListInsideTasksPidResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideTasksPidList(ctx, in, opts...)
}

// InsideVersion Rpc Start
func (m *defaultIntranet) InsideVersionAdd(ctx context.Context, in *AddInsideVersionReq, opts ...grpc.CallOption) (*InsideVersionCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideVersionAdd(ctx, in, opts...)
}

func (m *defaultIntranet) InsideVersionUpdate(ctx context.Context, in *UpdateInsideVersionReq, opts ...grpc.CallOption) (*InsideVersionCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideVersionUpdate(ctx, in, opts...)
}

func (m *defaultIntranet) InsideVersionDelete(ctx context.Context, in *DeleteInsideVersionReq, opts ...grpc.CallOption) (*InsideVersionCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideVersionDelete(ctx, in, opts...)
}

func (m *defaultIntranet) InsideVersionGet(ctx context.Context, in *GetInsideVersionReq, opts ...grpc.CallOption) (*ListInsideVersionData, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideVersionGet(ctx, in, opts...)
}

func (m *defaultIntranet) InsideVersionList(ctx context.Context, in *ListInsideVersionReq, opts ...grpc.CallOption) (*ListInsideVersionResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideVersionList(ctx, in, opts...)
}

// InsideHostInfo Rpc Start
func (m *defaultIntranet) InsideHostInfoAdd(ctx context.Context, in *AddInsideHostInfoReq, opts ...grpc.CallOption) (*InsideHostInfoCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideHostInfoAdd(ctx, in, opts...)
}

func (m *defaultIntranet) InsideHostInfoUpdate(ctx context.Context, in *UpdateInsideHostInfoReq, opts ...grpc.CallOption) (*InsideHostInfoCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideHostInfoUpdate(ctx, in, opts...)
}

func (m *defaultIntranet) InsideHostInfoDelete(ctx context.Context, in *DeleteInsideHostInfoReq, opts ...grpc.CallOption) (*InsideHostInfoCommonResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideHostInfoDelete(ctx, in, opts...)
}

func (m *defaultIntranet) InsideHostInfoGet(ctx context.Context, in *GetInsideHostInfoReq, opts ...grpc.CallOption) (*ListInsideHostInfoData, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideHostInfoGet(ctx, in, opts...)
}

func (m *defaultIntranet) InsideHostInfoList(ctx context.Context, in *ListInsideHostInfoReq, opts ...grpc.CallOption) (*ListInsideHostInfoResp, error) {
	client := intranetclient.NewIntranetClient(m.cli.Conn())
	return client.InsideHostInfoList(ctx, in, opts...)
}
