#!/bin/bash

##数据库中urls
sql="/admin
/admin/user
/admin/user/add
/admin/user/updateUserStatus
/admin/user/currentUser
/admin/user/delete
/admin/user/edit
/admin/user/getRouters
/admin/user/getUserAssignmentPolicy
/admin/user/list
/admin/user/login
/admin/user/logout
/admin/user/reSetPassword
/admin/user/selectAllData
/admin/user/update
/admin/user/updatePersonalData
/admin/user/updatePersonalPasswordData
/admin/user/userAssignmentPolicy
/admin/ugroup
/admin/ugroup/add
/admin/ugroup/delete
/admin/ugroup/getUgroupAssignmentPolicy
/admin/ugroup/list
/admin/ugroup/ugroupAssignmentPolicy
/admin/ugroup/update
/admin/stgroup
/admin/stgroup/add
/admin/stgroup/delete
/admin/stgroup/getDistributionConfig
/admin/stgroup/list
/admin/stgroup/policyAssociatedUsers
/admin/stgroup/update
/admin/role
/admin/role/add
/admin/role/delete
/admin/role/list
/admin/role/queryMenuByRoleId
/admin/role/update
/admin/role/updateRoleMenu
/admin/project
/admin/project/add
/admin/project/delete
/admin/project/list
/admin/project/update
/admin/menu
/admin/label
/admin/dept
/admin/dict
/admin/company
/admin/company/add
/admin/company/delete
/admin/company/list
/admin/company/update
/admin/dept/add
/admin/dept/delete
/admin/dept/list
/admin/dept/treeselect
/admin/dept/update
/admin/dict/add
/admin/dict/delete
/admin/dict/list
/admin/dict/type
/admin/dict/update
/admin/label/add
/admin/label/delete
/admin/label/list
/admin/label/update
/admin/menu/add
/admin/menu/delete
/admin/menu/list
/admin/menu/update
/admin/log
/admin/log/loginlog
/admin/log/syslog
/admin/stgroup/edit
/admin/resource
/admin/resource/add
/admin/resource/batchDelete
/admin/resource/list
/admin/resource/rsourceObjectValueList
/yunwei
/yunwei/asset
/yunwei/asset/add
/yunwei/asset/delete
/yunwei/asset/update
/yunwei/asset/list
/yunwei/keyManage
/yunwei/keyManage/add
/yunwei/keyManage/delete
/yunwei/keyManage/get
/yunwei/keyManage/list
/yunwei/keyManage/update
/yunwei/platform
/yunwei/platform/add
/yunwei/platform/delete
/yunwei/platform/get
/yunwei/platform/list
/yunwei/platform/update
/yunwei/featureServer
/yunwei/featureServer/add
/yunwei/featureServer/delete
/yunwei/featureServer/get
/yunwei/featureServer/list
/yunwei/featureServer/update
/yunying/maintainPlan
/yunying/maintainPlan/add
/yunying/maintainPlan/delete
/yunying/maintainPlan/get
/yunying/maintainPlan/list
/yunying/maintainPlan/update
/yunying/mergePlan
/yunying/mergePlan/add
/yunying/mergePlan/delete
/yunying/mergePlan/get
/yunying/mergePlan/list
/yunying/mergePlan/update
/yunying/openPlan
/yunying/openPlan/add
/yunying/openPlan/delete
/yunying/openPlan/get
/yunying/openPlan/list
/yunying/openPlan/update
/taskMng/taskQueue
/taskMng/taskQueue/add
/taskMng/taskQueue/delete
/taskMng/taskQueue/get
/taskMng/taskQueue/list
/taskMng/taskQueue/update
/admin/file
/admin/file/download
/admin/file/upload
/admin/search
/admin/search/article
/admin/strategy
/admin/strategy/list
/taskMng/taskLog
/taskMng/taskLog/list
/taskMng/taskLog/get
/yunwei/cluster
/yunwei/gameServer
/yunwei/hosts
/yunwei/cluster/list
/yunwei/gameServer/list
/yunwei/hosts/list
/taskMng/taskQueue/getTaskOperationList
/taskMng/taskQueue/getWebSocketAddr
/taskMng/taskQueue/start
/taskMng/taskQueue/stop
/yunwei/asset/assetInfoData
/yunwei/asset/ownerProjectData
/yunwei/asset/recycle
/yunwei/platform/detail
/yunwei/platform/project
/yunying/mergePlan/mergePlanRangeList
/yunying/maintainPlan/getMaintanListByPri
/yunying/maintainPlan/maintainGetClusterInfo
/yunying/maintainPlan/maintainPlanRangeList
/admin/log/terminallog
/admin/log/download
/taskMng/taskLogHistroy
/taskMng/taskLogHistroy/list
/taskMng/taskLogHistroy/detail
/yunwei/asset/getWebSshTree
"

##swgger文件
for i in admin.json yunwei.json;do
    ALL=$(egrep "/admin|/yunwei|/taskMng/|yunying" -A2 $i | grep -v -- "^--" | sed 'N;N;s/\n//g' |awk -F \" '{print $2" "$(NF-1)}'|sed "s/\/{.*\}//g"|sort)
    URL1=$(echo "$ALL"|awk -F '/' '{print $1"/"$2"/"$3}'|sort |uniq)
    URL2=$(echo "$ALL"|awk '{print $1}'|sort |uniq)
    URL3=$(echo "$ALL"|awk '{print $1" "$2}'|sort |uniq)
    T1+="$URL1\n$URL2\n"
    T2+="$URL3"
done
echo -e "/admin\n/yunwei\n$T1"|sort > 1
echo "$T2"|sort > 2
echo "$sql"|sort >3

##新增
mm=$(diff 1 3 |grep '<'|xargs echo |sed -e 's#< #|#g' -e 's#^|##g')
[ -n "$mm" ] && { echo "新增以下的地址" ; egrep "$mm" 2; } || echo "无新增地址"
