// Code generated by goctl. DO NOT EDIT.
// Source: monitor.proto

package server

import (
	"context"

	"ywadmin-v3/service/monitor/rpc/internal/logic"
	"ywadmin-v3/service/monitor/rpc/internal/svc"
	"ywadmin-v3/service/monitor/rpc/monitorclient"
)

type MonitorServer struct {
	svcCtx *svc.ServiceContext
	monitorclient.UnimplementedMonitorServer
}

func NewMonitorServer(svcCtx *svc.ServiceContext) *MonitorServer {
	return &MonitorServer{
		svcCtx: svcCtx,
	}
}

func (s *MonitorServer) ReportAdd(ctx context.Context, in *monitorclient.ReportAddReq) (*monitorclient.ReportAddResp, error) {
	l := logic.NewReportAddLogic(ctx, s.svcCtx)
	return l.ReportAdd(in)
}

func (s *MonitorServer) GraphList(ctx context.Context, in *monitorclient.GraphListReq) (*monitorclient.GraphListResp, error) {
	l := logic.NewGraphListLogic(ctx, s.svcCtx)
	return l.GraphList(in)
}

func (s *MonitorServer) SelectReport(ctx context.Context, in *monitorclient.SelectReportReq) (*monitorclient.SelectReportResp, error) {
	l := logic.NewSelectReportLogic(ctx, s.svcCtx)
	return l.SelectReport(in)
}
