// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	inws "ywadmin-v3/service/inws/api/internal/handler/inws"
	"ywadmin-v3/service/inws/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getInsideTasksLog",
				Handler: inws.GetInsideTasksLogHandler(serverCtx),
			},
		},
		rest.WithPrefix("/inws"),
	)
}
