// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	msgApi "ywadmin-v3/service/sendMsg/api/internal/handler/msgApi"
	"ywadmin-v3/service/sendMsg/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: msgApi.AddMsgApiHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: msgApi.ListMsgApiHandler(serverCtx),
			},
		},
		rest.WithPrefix("/sendMsg/msgApi"),
	)
}
