// Code generated by goctl. DO NOT EDIT.
package types

type GetProcessReq struct {
	Token  string `form:"token"`
	TaskId int64  `form:"taskId"`
}

type GetTaskRealTimeLogReq struct {
	Token string `form:"token"`
}

type GetWebSshReq struct {
	Token    string `form:"token"`
	Hostname string `form:"hostname"`
	SshPort  int64  `form:"sshPort,optional"`
	Cluster  string `form:"cluster,optional"`
}

type GetInstallLogReq struct {
	Token    string `form:"token"`
	GameName string `form:"gameName,optional"`
	FileName string `form:"fileName,optional"`
}
